breakfast_planner_online/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plan.urls')),
]

plan/urls.py
"""Defines URL patterns for plan"""

from django.urls import path

from . import views

app_name = 'plan' 
urlpatterns = [
    # Home page
    path('', views.index, name = 'index'),
    # Page that will show the plans
    path('personal_plans', views.personal_plans, name = 'personal_plans'),
    # Page that will show all food labels of a single Plan
    path('personal_plans/<int:personal_plan_id>/', views.personal_plan, 
        name='personal_plan'),
    # Page for adding a new plan
    path('new_personal_plan', views.new_personal_plan, name='new_personal_plan'),
    # Page for adding new food
    path('new_food/<int:personal_plan_id>/', views.new_food, name='new_food'),
    ]

plan/models.py
from django.db import models

# Create your models here.
class PersonalPlan(models.Model):
    """Name of the Plan"""
    plan_name = models.CharField(max_length=200)

    def __str__(self):
        """Returns name of plan name"""
        return self.plan_name

class FoodMainInformation(models.Model):
    """All main informations about the food"""
    perosnal_plan = models.ForeignKey(PersonalPlan, on_delete=models.CASCADE)
    food_label = models.CharField(max_length=200)
    food_description = models.TextField()
    # If food quantity is necessary the user have to input a number
    food_quantity_necessary = models.BooleanField()
    # if a reserve is necessary the creator have to input a number
    food_reserve_necessary = models.BooleanField()
    # If the value is zero, the calculated distribution factor is called
    maximum_distribution_of_food = models.IntegerField(default=0)

    def __str__(self):
        """Returns name of food label"""
        return f"{self.food_label}" #| {self.food_description[:20]}...

plan/forms.py
from django import forms
from .models import PersonalPlan, FoodMainInformation

class PersonalPlanForm(forms.ModelForm):
    class Meta:
        model = PersonalPlan
        fields = ['plan_name']
        labels = {'plan_name':''}

class FoodMainInformationForm(forms.ModelForm):
    class Meta:
        model = FoodMainInformation
        fields = ['food_label',
                    'food_description',
                    'food_quantity_necessary',
                    'food_reserve_necessary', 
                    'maximum_distribution_of_food']
        labels = {'food_label':'food_label', 
                    'food_description':'food_description',
                    'food_quantity_necessary':'food_quantity_necessary',
                    'food_reserve_necessary':'food_reserve_necessary',
                    'maximum_distribution_of_food':'maximum_distribution_of_food'}
        

plan/views.py
from django.shortcuts import render, redirect
from .models import PersonalPlan, FoodMainInformation
from .forms import PersonalPlanForm, FoodMainInformationForm

# Create your views here.

def index(request):
    """The home page of breakfast planner online"""
    return render(request, 'plan/index.html')

def personal_plans(request):
    """Show all plans"""
    personal_plans = PersonalPlan.objects.order_by()
    context = {'personal_plans':personal_plans}
    return render(request, 'plan/personal_plans.html', context)

def personal_plan(request, personal_plan_id):
    """Show all food labels and descriptions from oner personal plan"""
    personal_plan = PersonalPlan.objects.get(id=personal_plan_id)
    food_informations = personal_plan.foodmaininformation_set.all()    
    context = {'personal_plan':personal_plan, 'food_informations':food_informations}
    return render(request, 'plan/personal_plan.html', context)

def new_personal_plan(request):
    """Add new personal plan"""
    if request != 'POST':
        # No data submitted, create a blank form
        form = PersonalPlanForm()
    else:
        # Post data submitted, process data
        form = PersonalPlanForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('plan:personal_plans')

    # Display a blank or invalid form.
    context={'form':form}
    return render(request, 'plan/new_personal_plan.html', context)

def new_food(request, personal_plan_id):
    """Add new food"""
    personal_plan = PersonalPlan.objects.get(id=personal_plan_id)

    if request != 'POST':
        # No data submitted, create a blank form
        form = FoodMainInformationForm()
    else:
        # Post data submitted, process data
        form = FoodMainInformationForm(data=request.POST)
        if form.is_valid():
            new_food = form.save(commit=False)
            new_food.personal_plan = personal_plan
            new_food.save()
            return redirect('plan:personal_plan', personal_plan_id=personal_plan_id)
    
    # Display a blank or invalid form.
    context={'personal_plan':personal_plan, 'form':form}
    return render(request, 'plan/new_food.html', context)

plan/templates/plan/base.html
<!DOCTYPE html>
<html lang="de">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href={% url 'plan:index' %}>Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href={% url 'plan:index' %}>Home</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Dropdown link
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item" href={% url 'plan:personal_plans' %}>Planns</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                </ul>
             </div>
    </nav>



    <title>Titel der Seite | Name der Website</title>
  

  </head>
  <body>
        <div class="jumbotron">
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

plan/templates/plan/index.html
{% extends 'plan/base.html' %}

{% block content %}
        <h1>
        Help's you to plan your breakfast, for nice meetings with your friends </h1>
    </div>
{% endblock content %}

plan/templates/plan/new_food.html
{% extends 'plan/base.html' %}

{% block content %}
    <h2> <a href="{% url 'plan:personal_plan' personal_plan.id %}"></a></h2>

    <h3>Add new Food</h3>

    <form action="{% url 'plan:personal_plan' personal_plan.id %}" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <button name="submit">Add Food</button>
    </form>

{% endblock content %}

plan/templates/plan/new_personal_plan.html
{% extends 'plan/base.html' %}

{% block content %}
    <h2> Add a new Personal Plan</h2>

    <form action="{% url 'plan:new_personal_plan' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Add Plan</button>
    </form>

{% endblock content %}

plan/templates/plan/personal_plan.html
{% extends 'plan/base.html' %}

{% block content %}

    <h2> {{personal_plan}} </h2>

    <p>
        <a href="{% url 'plan:new_food' personal_plan.id %}">Add new Food</a>
    </p>

    <ul> 
        {% for food_information  in food_informations %}
            <li><h3>{{food_information.food_label}}</h3></li>
            <p>{{food_information.food_description}}</p>
        {% empty %}
            <li>No food have been added yet</li>
        {% endfor %}
    </ul>

    <!-- <ul> 
        {% for food_description  in food_description_list %}
            <li>{{food_description}}</li>
        {% empty %}
            <li>No food have been added yet</li>
        {% endfor %}
    </ul>

    

    <p> {{food_descriptions}} </p>-->
    

{% endblock content %}

plan/templates/plan/personal_plans.html
{% extends 'plan/base.html' %}
{% block content %}


    <h1> BREAKFASTPLAN PLAN </h1>

    <ul> 
        {% for personal_plan in personal_plans %}
            <li>
                <h3>
                <a href="{% url 'plan:personal_plan' personal_plan.id %}">
                {{personal_plan}}</a>
                </h3>
            </li>
        {% empty %}
            <li>No plans have been added yet</li>
        {% endfor %}
    </ul>

    <a href="{% url 'plan:new_personal_plan' %}">Add new Plan</a>

{% endblock content %}